export const LIBRARYDATA = {
  isSuccess: true,
  totalCount: 7,
  data: [
    {
      createdAt: '2022-12-06T01:34:48.140Z',
      entizenLibraryIdx: 1,
      title: '올해 전기차 보조금은?',
      link: 'https://post.naver.com/entizen_ev/',
      entizenImage: {
        createdAt: '2022-12-06T01:34:48.140Z',
        chargerProductFileIdx: 1,
        LibraryFileType: 'IMAGE',
        originalName: '이미지입니당',
        url: 'public/adminImages/libraryTestImage.png',
        size: 33498,
      },
    },
    {
      createdAt: '2022-11-06T01:34:48.140Z',
      entizenLibraryIdx: 2,
      title: '올해 전기차 보조금은? 2022년도 전기차 보조금을 알려드립니다.',
      link: 'https://post.naver.com/entizen_ev/',
      entizenImage: {
        createdAt: '2022-12-06T01:34:48.140Z',
        chargerProductFileIdx: 1,
        LibraryFileType: 'IMAGE',
        originalName: '이미지입니당',
        url: 'public/adminImages/libraryTestImage.png',
        size: 33498,
      },
    },
    {
      createdAt: '2022-10-06T01:34:48.140Z',
      entizenLibraryIdx: 1,
      title: '올해 전기차 보조금은?',
      link: 'https://post.naver.com/entizen_ev/',
      entizenImage: {
        createdAt: '2022-12-06T01:34:48.140Z',
        chargerProductFileIdx: 1,
        LibraryFileType: 'IMAGE',
        originalName: '이미지입니당',
        url: 'public/adminImages/libraryTestImage.png',
        size: 33498,
      },
    },
    {
      createdAt: '2022-09-06T01:34:48.140Z',
      entizenLibraryIdx: 1,
      title: '올해 전기차 보조금은?',
      link: 'https://post.naver.com/entizen_ev/',
      entizenImage: {
        createdAt: '2022-12-06T01:34:48.140Z',
        chargerProductFileIdx: 1,
        LibraryFileType: 'IMAGE',
        originalName: '이미지입니당',
        url: 'public/adminImages/libraryTestImage.png',
        size: 33498,
      },
    },
    {
      createdAt: '2022-08-06T01:34:48.140Z',
      entizenLibraryIdx: 1,
      title: '올해 전기차 보조금은?',
      link: 'https://post.naver.com/entizen_ev/',
      entizenImage: {
        createdAt: '2022-12-06T01:34:48.140Z',
        chargerProductFileIdx: 1,
        LibraryFileType: 'IMAGE',
        originalName: '이미지입니당',
        url: 'public/adminImages/libraryTestImage.png',
        size: 33498,
      },
    },
    {
      createdAt: '2022-07-06T01:34:48.140Z',
      entizenLibraryIdx: 1,
      title: '올해 전기차 보조금은?',
      link: 'https://post.naver.com/entizen_ev/',
      entizenImage: {
        createdAt: '2022-12-06T01:34:48.140Z',
        chargerProductFileIdx: 1,
        LibraryFileType: 'IMAGE',
        originalName: '이미지입니당',
        url: 'public/adminImages/libraryTestImage.png',
        size: 33498,
      },
    },
    {
      createdAt: '2022-06-06T01:34:48.140Z',
      entizenLibraryIdx: 1,
      title: '올해 전기차 보조금은?',
      link: 'https://post.naver.com/entizen_ev/',
      entizenImage: {
        createdAt: '2022-12-06T01:34:48.140Z',
        chargerProductFileIdx: 1,
        LibraryFileType: 'IMAGE',
        originalName: '이미지입니당',
        url: 'public/adminImages/libraryTestImage.png',
        size: 33498,
      },
    },
  ],
};
